# Generated by Django 5.0.3 on 2024-03-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_pic',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
